name: Compile and release

on:
  push:
    branches:
      main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV && echo "NOW=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Download dependencies and additional plugins
        working-directory: ${{ env.SCRIPTS_PATH }}/custom
        run: |
            sudo apt-get update && sudo apt-get install -y p7zip-full jq  # Install `p7zip-full` and `jq`
            wget -q -O tmp.zip https://github.com/agrastiOs/Ultimate-TF2-Visual-Fix-Pack/archive/refs/heads/master.zip && unzip -o tmp.zip -d mktemp/ && mv mktemp/Ultimate-TF2-Visual-Fix-Pack-master/TF2UltimateVisualFix/ ./ && rm -f tmp.zip && rm -rf mktemp/
            wget -q -O tmp.zip https://github.com/drunderscore/CastingEssentialsNext/releases/latest/download/CastingEssentialsNext.zip && unzip -o tmp.zip -d ./ && rm -rf CastingEssentialsNext/resource && rm -f tmp.zip
            wget -q -O tmp.zip https://github.com/CriticalFlaw/essentialsHUD/archive/refs/heads/fortress-faceoff.zip && unzip -o tmp.zip -d mktemp/ && rm -f mktemp/essentialsHUD-fortress-faceoff/resource/clientscheme.res && rsync -a --no-perms mktemp/essentialsHUD-fortress-faceoff/ essentialsHUD-fortress-faceoff/ && rm -f tmp.zip && rm -rf mktemp/
            wget -q https://github.com/mastercomfig/mastercomfig/releases/latest/download/mastercomfig-ultra-preset.vpk -O mastercomfig-ultra-preset.vpk
            wget -q https://github.com/mastercomfig/mastercomfig/releases/latest/download/mastercomfig-no-tutorial-addon.vpk -O mastercomfig-no-tutorial-addon.vpk           
      - name: Rename Readme
        working-directory: ${{ env.SCRIPTS_PATH }}
        run: |
            mv README.md readme.txt

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: |
          zip -qq -y -r "${{ github.event.repository.name }}.zip" custom cfg readme.txt
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: List files in the directory
        run: ls -R
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: List files in the zip
        run: unzip -l ${{ github.event.repository.name }}.zip
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.NOW }}
          artifacts: "${{ github.event.repository.name }}.zip"
          draft: false
          allowUpdates: true
          prerelease: false
          generateReleaseNotes: true
          replacesArtifacts: true